print('='*52)
print("|" + " "*20 + '|Morteza| ' + " "*20 + "|")
print("|" + " "*20 + '|AmirReza| ' + " "*19 + "|")
print("|" + " "*20 + '|Mahdiyar| ' + " "*19 + "|")
print("|" + " "*20 + '|Setayesh| ' + " "*19 + "|")
print("|" + " "*20 + '|Kimia| ' + " "*22 + "|")
print("|" + " "*20 + '|Nazanin| ' + " "*20 + "|")
print("|" + " "*20 + '|Matin| ' + " "*22 + "|")
print('='*52)
